# ~/.zshrc
#line cursor
# printf '\e[6 q'

# Only continue for interactive shells.
[[ $- == *i* ]] || return
# Environment
typeset -U path PATH
path=(
  "$HOME/.local/bin"
  $path
)

export EDITOR=nvim
export VISUAL=$EDITOR
export BAT_PAGER=''
export EZA_COLORS='di=38;2;245;194;231:ex=38;2;148;226;213:ln=38;2;180;190;254:or=38;2;243;139;168:*.go=38;2;148;226;213:*.lua=38;2;137;180;250:*.md=38;2;180;190;254:*.json=38;2;250;179;135:*.yaml=38;2;203;166;247:*.yml=38;2;203;166;247:*.toml=38;2;245;194;231:*.sh=38;2;148;226;213:*.Dockerfile=38;2;116;199;236:Dockerfile=38;2;116;199;236'

# Claude Code via Yum LiteLLM
export ANTHROPIC_BASE_URL='https://litellm.shd.yumconnect.dev'
export ANTHROPIC_DEFAULT_HAIKU_MODEL='haiku (bedrock)'
export ANTHROPIC_DEFAULT_SONNET_MODEL='sonnet (bedrock)'
export ANTHROPIC_DEFAULT_OPUS_MODEL='opus (bedrock)'
export CLAUDE_CODE_USE_BEDROCK=0
export CLAUDE_CODE_API_KEY_HELPER_TTL_MS=21600000
unset ANTHROPIC_MODEL

export TMUX_TMPDIR="$HOME/.tmux/tmp"
export DOOMDIR="$HOME/.config/doom"
export EMACSDIR="$HOME/.config/emacs"
export AWS_CLI_AUTO_PROMPT=on-partial

# Shell options
unsetopt BEEP HIST_BEEP LIST_BEEP
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY

# Plugins and completion
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=''
plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting)
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Optional tools
if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh --cmd cd)"
fi

if (( $+commands[atuin] )); then
  eval "$(atuin init zsh)"
fi

if (( $+commands[starship] )); then
  eval "$(starship init zsh)"
fi

# Aliases
alias cat='bat --paging=never --style=grid,header'
alias grep='grep --color=auto'
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias k='kubectl'
alias kon='export K8S_ACTIVE=1'
alias koff='unset K8S_ACTIVE'
alias n='nvim'
alias cc='claude'
alias oc='opencode'
alias eza='eza --icons=always'
alias ls='eza --icons=always --group-directories-first'
alias g++='g++-16'
alias gcc='gcc-16'

# Change to the directory selected in Yazi when it exits.
if (( $+commands[yazi] )); then
  y() {
    local tmp cwd
    tmp="$(mktemp -t yazi-cwd.XXXXXX)"
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [[ -n $cwd && $cwd != "$PWD" ]]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  }
fi

# Load Node.js only when its commands are first used.
if [[ -s $HOME/.nvm/nvm.sh ]]; then
  nvm() {
    unset -f nvm node npm npx gemini codex
    export NVM_DIR="$HOME/.nvm"
    source "$NVM_DIR/nvm.sh"
    [[ -s $NVM_DIR/bash_completion ]] && source "$NVM_DIR/bash_completion"
    nvm "$@"
  }
  node() { nvm >/dev/null && command node "$@"; }
  npm() { nvm >/dev/null && command npm "$@"; }
  npx() { nvm >/dev/null && command npx "$@"; }
  gemini() { nvm >/dev/null && command gemini "$@"; }
fi

# Key bindings
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char
bindkey '^U' backward-kill-line
bindkey '^K' kill-line
bindkey '^W' backward-kill-word

# Show the current command in the terminal tab title.
_set_tab_title() {
  printf '\e]0;%s\a' "${1:-zsh}"
}

preexec() {
  _set_tab_title "${1%% *}"
}

precmd() {
  _set_tab_title zsh
}

# Generated by envman.
[[ -s $HOME/.config/envman/load.sh ]] && source "$HOME/.config/envman/load.sh"
